name: Daily Streak

on:
  schedule:
    # Roz 00:00 UTC (India me approx 5:30 AM)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "$(date)" >> timestamp.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "rohitgcode20@gmail.com"

          git add timestamp.txt
          git commit -m "Daily streak update" || exit 0
          git push
